project:
  type: website
  output-dir: docs
website:
  title: "Shabanov Ragim website"
  navbar:
    left:
      - href: index.qmd
        text: PH Days Standoff
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



